language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
after_success:
  - chmod +x ./publish.sh
  - ./publish.sh
  - yarn lh -- https://freader.netlify.com
branches:
  only:
    - master
notifications:
  email:
    on_success: never 
    on_failure: always

